### ISSUE TITLE
Non KYC verified user was able to participate in Survey Completion.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov#4]
14/12/21 Contract: freeosgov, account: ellaevery type: e, Version# v0.7.5, Bloks.io
Was able to participate in survey completion for ellaevery account type 'e'. Expecting survey participation to be restricted to KYC verified users only.
Steps:
1. Register ellaevery
2. Run Survey action for user ellaevery at 03:12:21 PM within the Survey start/end time.
3. Survey successful.

![Account - Proton Testnet 14-12-2021 13-35-18](https://user-images.githubusercontent.com/77765830/145911282-bdb180cc-de57-4739-b324-b38d2fd24a0f.png)

**Comment by tommccann777** [comment]
I had temporarily set the 'is verified' check to allow all statuses v, b, c and e to enable developer testing. I have corrected this and removed the 'e'. I have redeployed as version 0.7.6.

**Comment by judytan21** [comment]
15/12/21 Retest scenario. Contract: freeosgov, account: ellaevery type: e, Version# v0.7.6, Bloks.io
Was still able to complete survey for ellaevery account type 'e'. Screenshot attached.
However, ellaevery was unable to vote.
Partially fixed. 
Survey successful
![Account - Proton Testnet 15-12-2021 17-17-05](https://user-images.githubusercontent.com/77765830/146122987-a3201d0d-eb20-46c9-9cf2-0393f8657821.png)
Vote unsuccessful
![Account - Proton Testnet 15-12-2021 17-28-21](https://user-images.githubusercontent.com/77765830/146123430-5b407f89-9616-4cd3-8a73-061619f6d1c0.png)

**Comment by judytan21** [comment]
20/12/21 Retest V0.7.9 after discussing w/ Tom, ellaevery registered but account type 'e'
Error: assertion failure with message: survey is not open to unverified users
Fixed. Close.
